name: Integration Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run-integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Add timeout to prevent hanging
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'  # Cache npm dependencies for faster runs

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser libgbm-dev  # Additional dependencies for headless Chrome
          npm ci  # Use ci for clean installs in CI environments

      - name: Verify Chrome installation
        run: |
          chromium-browser --version
          which chromium-browser

      - name: Run Jest integration tests
        run: |
          xvfb-run --auto-servernum npx jest tests/voicely.test.js \
            --detectOpenHandles \
            --forceExit \
            --verbose \
            --reporters=default \
            --reporters=jest-junit
        env:
          CI: true
          DISPLAY: ':99'  # Required for Xvfb
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true  # We're using system Chrome
          PUPPETEER_EXECUTABLE_PATH: '/usr/bin/chromium-browser'

      - name: Upload test results
        if: always()  # Run even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            screenshots/
            test-report.xml